name: compress InstallAssistaant.pkg
on: [push]

jobs:
  compress:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: compress pkg
        run: |
          brew install zstd
          curl -O https://swcdn.apple.com/content/downloads/28/04/062-39980-A_E2QPJBGQ4F/bg46pvbieyqap91k8idx3anrem2ip80bcq/InstallAssistant.pkg
          tar cf InstallAssistant.pkg.tar InstallAssistant.pkg
          zstd -19 InstallAssistant.pkg.tar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.5
        with:
          path: ./InstallAssistant.pkg.tar.zst
